@startuml
title Парадигмы программирования

class Императивное {
    + последовательные операции
    + изменяемость состояний
}

class Декларативное {
    + описание желаемого результата
    + отсутствие явных инструкций
}

class Структурное {
    + разбиение программы на блоки
    + использование функций и процедур
}

class Неструктурное {
    + отсутствие явной структуры
    + использование безусловных переходов
}

class Процедурное {
    + процедуры и функции
    + переменные и константы
    + операторы управления потоком
}

class Объектно_ориентированное {
    + инкапсуляция
    + наследование
    + полиморфизм
}

class Функциональное {
    + функции высшего порядка
    + рекурсия
    + неизменяемость данных
}

class Прототипное {
    + создание объектов на основе прототипов
    + динамическое изменение объектов
}

class Аппликативное {
    + применение функций к аргументам
    + отсутствие побочных эффектов

}

class Комбинаторное {
    + комбинирование функций для получения новых функций
    + отсутствие переменных и состояний

}
class На_основе_классов  {
}

Императивное --> Структурное
Декларативное --> Логическое
Императивное --> Неструктурное
Декларативное --> Функциональное
Структурное --> Процедурное
Структурное --> Объектно_ориентированное
Структурное ..> Функциональное
Объектно_ориентированное --> Прототипное
Объектно_ориентированное --> На_основе_классов
Функциональное --> Аппликативное
Функциональное --> Комбинаторное

@enduml
